services:
  php:
    container_name: ligaac-api
    build:
      context: ./docker  # Corrected this line from additional_contexts to context
    volumes:
      - ./:/srv/app/
      # Uncomment the following lines to speed up the app on Windows (note that on the first run they should be commented
      # so the files in the host machine get in sync with the container files)
      #- /srv/app/var
      #- /srv/app/vendor
    environment:
      TZ: Europe/Bucharest
      DATABASE_URL: mysql://user:password@database:3306/app?serverVersion=8.3.0&charset=utf8mb4
    restart: unless-stopped
    ports:
      - '80:80'
  database:
    container_name: ligaac-db
    image: mysql:8.3.0
    volumes:
      - database_data:/var/lib/mysql/:rw
    environment:
      TZ: Europe/Bucharest
      MYSQL_DATABASE: app
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
      MYSQL_PASSWORD: password
      MYSQL_USER: user
    restart: unless-stopped
    ports:
      - '53306:3306'

volumes:
  database_data:
